/**
 * @fileoverview Arecibo Expression Engine
 * Main integration point: assembles week context, calls LLM if budget allows,
 * generates AreciboIntent with fallback to templates
 *
 * Core contract:
 * - Input: weekData (from factStore), bondLevel, tasteProfile, llmBudget
 * - Output: AreciboIntent matching the spec
 * - Fallback: deterministic template when LLM unavailable
 * - Timeout: 8 seconds (don't block UI)
 */

import { getAreciboSystemPrompt } from './areciboPrompts.js';
import {
  validateEmotionalGuardrails,
  validateReflectionDerivative,
  validateSignalDerivative,
  validateAreciboIntent,
} from './emotionalGuardrails.js';
import { composeSignalMessage } from './signalComposer.js';
import {
  selectCountDerivative,
  selectElementsDerivative,
  selectPatternDerivative,
  selectThreadDerivative,
  selectReflectionDerivative,
  selectKingdomDerivative,
  selectSignalDerivative,
} from './derivativeSelector.js';

/**
 * Generate full AreciboIntent for the week
 * Tries LLM first, falls back to templates if unavailable
 *
 * @param {Object} params
 * @param {Object} params.weekData - Aggregated weekly facts (bills, habits, meetings, etc.)
 * @param {1|2|3|4|5} params.bondLevel - Bond Level (1-5)
 * @param {Object} params.tasteProfile - User preferences {favoriteSymbols, favoriteSources, faithMode, ...}
 * @param {number} [params.llmBudget=1] - Number of LLM calls available this cycle (0 = fallback only)
 * @param {Object} [params.llmService] - LLM service instance (defaults to no-op if not provided)
 * @param {Object} [params.previousWeekData] - Optional previous week for callbacks
 * @returns {Promise<Object>} AreciboIntent { weekNumber, sections: {...} }
 */
export async function generateAreciboIntent({
  weekData,
  bondLevel = 1,
  tasteProfile = {},
  llmBudget = 1,
  llmService = null,
  previousWeekData = null,
}) {
  // If we have LLM budget and service, try to call LLM
  if (llmBudget > 0 && llmService) {
    try {
      const llmIntent = await callAreciboLLM({
        weekData,
        bondLevel,
        tasteProfile,
        llmService,
      });

      // Validate the LLM output against emotional guardrails
      const validation = validateAreciboIntent(llmIntent, weekData, tasteProfile);
      if (validation.valid) {
        return llmIntent;
      }

      // If validation failed with critical errors, log and fall through to templates
      console.warn('Arecibo LLM validation failed (using templates):', validation.errors);
    } catch (error) {
      console.warn('Arecibo LLM call failed, using template fallback:', error.message);
    }
  }

  // Fallback: deterministic templates
  return generateFromTemplates({
    weekData,
    bondLevel,
    tasteProfile,
    previousWeekData,
  });
}

/**
 * Call Claude Sonnet to generate AreciboIntent
 * Timeout: 8 seconds (don't block UI)
 *
 * @param {Object} params
 * @returns {Promise<Object>} AreciboIntent
 */
async function callAreciboLLM({
  weekData,
  bondLevel,
  tasteProfile,
  llmService,
}) {
  const systemPrompt = getAreciboSystemPrompt({
    companionName: weekData.companionName || 'Companion',
    userName: tasteProfile.userName || 'friend',
    weekSentiment: weekData.weekSentiment,
    bondLevel,
  });

  const userPrompt = buildLLMUserPrompt(weekData, tasteProfile);

  // Wrap in timeout
  const timeoutPromise = new Promise((_, reject) =>
    setTimeout(() => reject(new Error('Arecibo LLM timeout (8s)')), 8000)
  );

  try {
    const response = await Promise.race([
      llmService.call({
        model: 'claude-3-5-sonnet-20241022', // Sonnet class for quality
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      }),
      timeoutPromise,
    ]);

    // Parse JSON response
    let intent;
    try {
      // LLM should return ONLY JSON, but strip markdown if present
      const jsonStr = response.content
        .replace(/^```json\n?/, '')
        .replace(/\n?```$/, '')
        .trim();
      intent = JSON.parse(jsonStr);
    } catch (parseError) {
      throw new Error(`Failed to parse Arecibo JSON: ${parseError.message}`);
    }

    // Add week number (not generated by LLM)
    intent.weekNumber = weekData.weekNumber;

    // Validate structure
    if (!intent.sections) {
      throw new Error('LLM response missing sections object');
    }

    return intent;
  } catch (error) {
    throw error;
  }
}

/**
 * Build the user prompt for LLM
 * Provides week context in a structured format
 *
 * @param {Object} weekData
 * @param {Object} tasteProfile
 * @returns {string}
 */
function buildLLMUserPrompt(weekData, tasteProfile) {
  return `
# This Week's Facts

## Bills
- Paid: ${weekData.billsPaid} / ${weekData.billsTotal}

## Habits
${weekData.activeHabits
  .map((h) => `- ${h.name}: ${h.completed} / ${h.total} days`)
  .join('\n')}

## Engagement
- Meetings: ${weekData.meetings}
- Days active: ${weekData.daysActive} / 7
- XP earned: ${weekData.bondXpEarned}

## Progress
${
  weekData.longestStreak
    ? `- Longest streak: ${weekData.longestStreak.days} days (${weekData.longestStreak.habit})`
    : '- No active streaks'
}
${
  weekData.nearestMilestone
    ? `- Next milestone: ${weekData.nearestMilestone.daysAway} days away (${weekData.nearestMilestone.type})`
    : ''
}

## Daily Intensity (0-10 scale)
${weekData.dailyIntensity.map((intensity, day) => `- ${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][day]}: ${intensity}`).join('\n')}

## User Profile
- Kingdom: ${weekData.kingdomName}
- Bond Level: ${weekData.bondLevel}
${tasteProfile.favoriteSymbols ? `- Favorite symbols: ${tasteProfile.favoriteSymbols.join(', ')}` : ''}
${tasteProfile.favoriteSources ? `- Favorite thinkers: ${tasteProfile.favoriteSources.join(', ')}` : ''}
${tasteProfile.faithMode ? '- Faith mode enabled' : ''}

---

Now generate the Arecibo Recap for this week. Choose one derivative per section based on the week's facts and character.
Remember: no therapy-speak, no guilt, no fake triumph. Be direct and honest. Respect the hard-week dignity protocol.
`;
}

/**
 * Fallback: generate AreciboIntent from deterministic templates
 * No creativity, no LLM needed, still beautiful and unique
 *
 * Uses derivativeSelector to pick one derivative per section,
 * then templates to fill in the message content
 *
 * @param {Object} params
 * @returns {Object} AreciboIntent
 */
function generateFromTemplates({
  weekData,
  bondLevel,
  tasteProfile,
  previousWeekData,
}) {
  return {
    weekNumber: weekData.weekNumber,
    sections: {
      count: {
        derivative: selectCountDerivative(weekData, bondLevel),
        stats: {
          billsPaid: weekData.billsPaid,
          habitsCompleted: weekData.habitsCompleted,
          meetings: weekData.meetings,
          daysActive: weekData.daysActive,
          xpEarned: weekData.bondXpEarned,
        },
      },
      elements: {
        derivative: selectElementsDerivative(weekData, bondLevel),
        habits: weekData.activeHabits || [],
      },
      pattern: {
        derivative: selectPatternDerivative(weekData, bondLevel),
        dailyIntensity: weekData.dailyIntensity || [],
        narrative: getPatternNarrative(weekData.dailyIntensity),
      },
      thread: {
        derivative: selectThreadDerivative(weekData, bondLevel),
        longestStreak: weekData.longestStreak || { habit: '', days: 0 },
        weeksEngaged: weekData.weeksEngaged || 1,
        nearestMilestone: weekData.nearestMilestone || { type: '', daysAway: 0, target: 0 },
      },
      reflection: {
        derivative: selectReflectionDerivative(weekData, bondLevel),
        weekSentiment: weekData.weekSentiment,
        heldItem: getHeldItem(weekData, tasteProfile, bondLevel),
      },
      kingdom: {
        derivative: selectKingdomDerivative(weekData, bondLevel),
        spotlightObject: null, // Set by kingdom data
        totalStructures: 0, // Set by kingdom data
        addedThisWeek: 0, // Set by kingdom data
      },
      signal: composeSignalMessage({
        weekData,
        bondLevel,
        tasteProfile,
        previousWeekData,
      }),
    },
  };
}

/**
 * Get a narrative description of the week's daily pattern
 * @param {number[]} dailyIntensity - Array of 7 intensity values (0-10)
 * @returns {string}
 */
function getPatternNarrative(dailyIntensity) {
  if (!dailyIntensity || dailyIntensity.length !== 7) {
    return 'steady week';
  }

  const start = dailyIntensity.slice(0, 3).reduce((a, b) => a + b, 0) / 3;
  const mid = dailyIntensity.slice(2, 5).reduce((a, b) => a + b, 0) / 3;
  const end = dailyIntensity.slice(4, 7).reduce((a, b) => a + b, 0) / 3;

  if (start > end) return 'slow_finish';
  if (end > start) return 'strong_finish';
  if (Math.max(...dailyIntensity) > 8) return 'peaks_present';
  if (Math.min(...dailyIntensity) < 3) return 'valleys_present';

  return 'steady_week';
}

/**
 * Determine what item the reflection figure should hold
 * Bond Level gate: higher levels can use personal items
 *
 * @param {Object} weekData
 * @param {Object} tasteProfile
 * @param {1|2|3|4|5} bondLevel
 * @returns {string|null}
 */
function getHeldItem(weekData, tasteProfile, bondLevel) {
  if (bondLevel < 3) {
    return null; // Generic sword/shield, not personalized
  }

  // Bond 3+: can hold items from taste profile
  if (tasteProfile?.favoriteItems?.length > 0) {
    return tasteProfile.favoriteItems[0];
  }

  // Fallback based on week sentiment
  if (weekData.weekSentiment === 'victory') {
    return 'sword'; // Celebratory/triumphant
  }
  if (weekData.weekSentiment === 'tough') {
    return 'shield'; // Defensive/protective
  }

  return 'staff'; // Neutral
}

/**
 * Validate that an AreciboIntent output respects all constraints
 *
 * @param {Object} areciboIntent
 * @param {Object} weekData
 * @param {Object} tasteProfile
 * @returns {{ valid: boolean, errors: string[], warnings: string[] }}
 */
export function validateAreciboOutput(areciboIntent, weekData, tasteProfile) {
  return validateAreciboIntent(areciboIntent, weekData, tasteProfile);
}

/**
 * Utility: assemble week context from factStore
 * This is called by the weekly loop to gather data before passing to expressionEngine
 *
 * @param {Object} params
 * @param {Object} params.factStore - Facts database/store
 * @param {number} params.weekNumber - Week index
 * @returns {Object} WeekData ready for expressionEngine
 */
export function assembleWeekContext({
  factStore,
  weekNumber,
  habitsStore,
  kingdomStore,
}) {
  // Pseudo-code: this would be filled in with actual store queries
  // For now, shows the structure

  const weekStart = getWeekStart(weekNumber);
  const weekEnd = getWeekEnd(weekNumber);

  const billsFacts = (factStore.bills || []).filter(
    (b) => b.dateLogged >= weekStart && b.dateLogged <= weekEnd
  );
  const habitFacts = (factStore.habits || []).filter(
    (h) => h.dateLogged >= weekStart && h.dateLogged <= weekEnd
  );
  const meetingFacts = (factStore.meetings || []).filter(
    (m) => m.dateLogged >= weekStart && m.dateLogged <= weekEnd
  );

  const billsPaid = billsFacts.filter((b) => b.paid).length;
  const billsTotal = billsFacts.length;
  const habitsCompleted = habitFacts.filter((h) => h.completed).length;
  const habitsTotal = habitFacts.length;

  // Compute sentiment
  const weekSentiment = computeWeekSentiment(billsPaid, billsTotal, habitsCompleted, habitsTotal);

  return {
    weekNumber,
    billsPaid,
    billsTotal,
    habitsCompleted,
    habitsTotal,
    meetings: meetingFacts.length,
    daysActive: 0, // Count unique dates from all facts
    bondXpEarned: 0, // From progression system
    activeHabits: [], // From habits store
    dailyIntensity: [0, 0, 0, 0, 0, 0, 0], // Computed from facts
    longestStreak: null,
    nearestMilestone: null,
    weekSentiment,
    bondLevel: 1, // From progression
    companionName: 'Companion',
    kingdomName: 'Kingdom',
  };
}

/**
 * Determine week sentiment based on bills and habits
 * tough: bills > paid*1.5 OR habits < total*0.5
 * victory: all bills paid AND habits > total*0.8
 * mixed: everything else
 *
 * @param {number} billsPaid
 * @param {number} billsTotal
 * @param {number} habitsCompleted
 * @param {number} habitsTotal
 * @returns {'victory' | 'tough' | 'mixed'}
 */
export function computeWeekSentiment(billsPaid, billsTotal, habitsCompleted, habitsTotal) {
  const billStress = billsTotal > 0 && billsPaid < billsTotal * 0.5;
  const habitStress = habitsTotal > 0 && habitsCompleted < habitsTotal * 0.5;
  const billsCleared = billsTotal > 0 && billsPaid === billsTotal;
  const habitsStrong = habitsTotal > 0 && habitsCompleted > habitsTotal * 0.8;

  if (billStress || habitStress) {
    return 'tough';
  }
  if (billsCleared && habitsStrong) {
    return 'victory';
  }
  return 'mixed';
}

// Helper: stub implementations (would come from actual store)
function getWeekStart(weekNumber) {
  return new Date(2024, 0, weekNumber * 7);
}

function getWeekEnd(weekNumber) {
  return new Date(2024, 0, (weekNumber + 1) * 7);
}
